---

- name: ensure tasks run only on selected os releases
  block:

    - name: enable epel related repositories
      ansible.builtin.include_role:
        name: repo__epel

    - name: ensure tasks run only on selected os releases
      block:

        - name: install powerline packages
          ansible.builtin.package:
            name: "{{ powerline.packages.base | ansible.builtin.union(powerline.packages.red_hat) }}"

      when: >
        ansible_distribution == "CentOS" or
        ansible_distribution == "Fedora" or
        ansible_distribution == "RedHat" or
        ansible_distribution == "Rocky"

    - name: install powerline packages
      ansible.builtin.package:
        name: "{{ powerline.packages.base | ansible.builtin.union(powerline.packages.arch) }}"
      when: ansible_distribution == "Archlinux"

    - name: locate powerline-bash script
      shell:
        cmd: find / -name powerline.sh | grep -i bash
      changed_when: false
      register: cmd_bash_powerline

    - debug:
        var: cmd_bash_powerline
        verbosity: 1

    - name: configure powerline for bash
      template:
        src: templates/powerline-bash.sh
        dest: /etc/profile.d/powerline-bash.sh
        owner: root
        group: root
        mode: "0644"

    - name: configure powerline for tmux
      template:
        src: templates/powerline-tmux.sh
        dest: /etc/profile.d/powerline-tmux.sh
        owner: root
        group: root
        mode: "0644"

    - name: configure powerline for vim
      template:
        src: templates/powerline-vim.sh
        dest: /etc/profile.d/powerline-vim.sh
        owner: root
        group: root
        mode: "0644"

  when: >
    ansible_distribution == "Archlinux" or
    ansible_distribution == "CentOS" or
    ansible_distribution == "Fedora" or
    ansible_distribution == "RedHat" or
    ansible_distribution == "Rocky"

...
